/* =================================================================
 *                     conneXience Data Pipeline
 * =================================================================
 *
 * Copyright 2006 Hugo Hiden and Adrian Conlin
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.pipeline.core.drawing.customio.editing;
import org.pipeline.core.drawing.customio.*;

/**
 * This panel provides a way of configuring inputs and outputs for a custom port definition
 * list.
 * @author  hugo
 */
public class CustomPortDefinitionListEditor extends javax.swing.JPanel {
    /** Port definition list */
    private CustomPortDefinitionList portDefs;
    
    /** Selected definition */
    private CustomPortDefinition selectedDef = null;
    
    /** Creates new form CustomPortDefinitionListEditor */
    public CustomPortDefinitionListEditor(CustomPortDefinitionList portDefs) {
        initComponents();
        // Localise labels
        addButton.setText("Add");
        deleteButton.setText("Delete");
        jPanel1.setBorder(new javax.swing.border.TitledBorder("Port Details"));
        jLabel2.setText("Location");
        jLabel3.setText("Offset");

        this.portDefs = portDefs;
        createModel();
        
        // Create the location text
        javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel();
        model.addElement("Left of block");
        model.addElement("Top of block");
        model.addElement("Right of block");
        model.addElement("Bottom of block");
        locationCombo.setModel(model);
        displaySelected();
    }
    
    /** Create the port list model */
    private void createModel(){
        if(portDefs!=null){
            javax.swing.DefaultListModel model = new javax.swing.DefaultListModel();
            for(int i=0;i<portDefs.getDefinitionCount();i++){
                model.addElement(portDefs.getDefinition(i));
            }
            portList.setModel(model);
        } else {
            portList.setModel(new javax.swing.DefaultListModel());
        }
    }
    
    /** Display the selected port */
    private void displaySelected(){
        if(selectedDef!=null){
            locationCombo.setEnabled(true);
            portOffset.setEnabled(true);
            portOffset.setValue(selectedDef.getOffset());
            locationCombo.setSelectedIndex(selectedDef.getLocation());            
        } else {
            locationCombo.setEnabled(false);
            portOffset.setEnabled(false);
            portOffset.setValue(0);
        }
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        locationCombo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        portOffset = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        portList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/pipeline/core/drawing/resource/Add16.gif")));
        addButton.setText("Add");
        addButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jPanel6.add(addButton);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/pipeline/core/drawing/resource/Delete16.gif")));
        deleteButton.setText("Delete");
        deleteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel6.add(deleteButton);

        jPanel5.add(jPanel6, java.awt.BorderLayout.NORTH);

        add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Port details"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Location");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 15));
        jPanel3.add(jLabel2, java.awt.BorderLayout.WEST);

        locationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboActionPerformed(evt);
            }
        });

        jPanel3.add(locationCombo, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Offset");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 15));
        jPanel4.add(jLabel3, java.awt.BorderLayout.WEST);

        portOffset.setMajorTickSpacing(10);
        portOffset.setMinorTickSpacing(5);
        portOffset.setPaintTicks(true);
        portOffset.setSnapToTicks(true);
        portOffset.setValueIsAdjusting(true);
        portOffset.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                portOffsetStateChanged(evt);
            }
        });

        jPanel4.add(portOffset, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel2.add(jPanel1, java.awt.BorderLayout.SOUTH);

        portList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                portListMousePressed(evt);
            }
        });

        jScrollPane1.setViewportView(portList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    /** Create a new definition */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String name = javax.swing.JOptionPane.showInputDialog(null, "Enter Port name", "Question", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if(name!=null){
            if(!portDefs.namedDefinitionPresent(name)){
                selectedDef = portDefs.createDefinition(name);
                portDefs.syncParentIOs();
                createModel();
                displaySelected();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Selected port name already exists", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    /** Delete selected def */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(selectedDef!=null){
            portDefs.removeDefintion(selectedDef);
            portDefs.syncParentIOs();
            selectedDef = null;
            createModel();
            displaySelected();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void portOffsetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_portOffsetStateChanged
        if(selectedDef!=null){
            selectedDef.setOffset(portOffset.getValue());
            portList.repaint();
            portDefs.syncParentIOs();
        }
    }//GEN-LAST:event_portOffsetStateChanged

    /** Set selected location */
    private void locationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboActionPerformed
        if(selectedDef!=null){
            selectedDef.setLocation(locationCombo.getSelectedIndex());
            portList.repaint();
            portDefs.syncParentIOs();
        }
    }//GEN-LAST:event_locationComboActionPerformed

    /** Set the offset when focus is lost */
    /** Handle key typed */
    /** Mouse pressed on editor */
    private void portListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portListMousePressed
        if(portList.getSelectedValue()!=null){
            selectedDef = (CustomPortDefinition)portList.getSelectedValue();
        } else {
            selectedDef = null;
        }
        displaySelected();
    }//GEN-LAST:event_portListMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox locationCombo;
    private javax.swing.JList portList;
    private javax.swing.JSlider portOffset;
    // End of variables declaration//GEN-END:variables
    
}
