/* =================================================================
 *                     conneXience Data Pipeline
 * =================================================================
 *
 * Copyright 2006 Hugo Hiden and Adrian Conlin
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.pipeline.gui.xmlstorage;

/**
 * This class provides a panel to edit an XmlDataObject
 * @author  hugo
 */
public class XmlDataObjectPanel extends javax.swing.JPanel {
    /** Central panel */
    private javax.swing.JPanel centralPanel = null;
    
    /** Creates new form XmlDataObjectPanel */
    public XmlDataObjectPanel() {
        initComponents();
    }
    
    /** Set the central panel */
    public void setCentralPanel(javax.swing.JPanel centralPanel){
        centralPanel = centralPanel;
    }
    
    /** Show the central panel */
    public void showCentralPanel(){
        
    }
    
    /** Hide the central panel */
    public void hideCentralPanel(){
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        topPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        expandButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        topPanel.setLayout(new java.awt.BorderLayout(10, 0));

        nameLabel.setText("jLabel1");
        topPanel.add(nameLabel, java.awt.BorderLayout.CENTER);

        expandButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/goldproject/gui/common/resource/Plus.gif")));
        expandButton.setContentAreaFilled(false);
        expandButton.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel1.add(expandButton);

        topPanel.add(jPanel1, java.awt.BorderLayout.WEST);

        add(topPanel, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(50, 1));
        add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.BorderLayout());

        add(jPanel3, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton expandButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
    
}
