/*
 * XmlDataStoreEditorDialog.java
 *
 * Created on October 23, 2007, 5:25 PM
 */

package org.pipeline.gui.xmlstorage;
import org.pipeline.core.xmlstorage.*;

/**
 * This dialog provides an editor for an XmlDataStore object
 * @author  nhgh
 */
public class XmlDataStoreEditorDialog extends javax.swing.JDialog {
    /** Property store */
    private XmlDataStore properties;
    
    /** Editor */
    private XmlDataStoreEditor editor;
    
    /** Was the dialog accepted */
    private boolean accepted = false;
    
    /** Creates new form XmlDataStoreEditorDialog */
    public XmlDataStoreEditorDialog(XmlDataStore properties) {
        super();
        setModal(true);
        initComponents();
        editor = new XmlDataStoreEditor();
        getContentPane().add(editor, java.awt.BorderLayout.CENTER);
        pack();
        setSize(300, 400);        
        setLocationRelativeTo(null);
        this.properties = properties;
        editor.setStore(properties);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        editor.updateValues();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
