/* =================================================================
 *                     conneXience Data Pipeline
 * =================================================================
 *
 * Copyright 2006 Hugo Hiden and Adrian Conlin
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.pipeline.gui.xmlstorage.xmldatatypes;
import org.pipeline.gui.xmlstorage.*;
import org.pipeline.core.xmlstorage.*;
import org.pipeline.core.xmlstorage.xmldatatypes.*;

import java.awt.Color;

/**
 * This class edits a XmlColorDataObject
 * @author  hugo
 */
public class XmlColorDataObjectEditor extends javax.swing.JPanel implements XmlDataObjectEditor {
    /** Object being edited */
    private XmlColorDataObject colorObject = null;
    
    /** Width of caption */
    private int captionWidth = 0;
    
    /** Creates new form XmlColorDataObjectEditor */
    public XmlColorDataObjectEditor() {
        initComponents();
    }

    /** Set the object being edited */
    public void setObject(XmlDataObject object) {
        colorObject = (XmlColorDataObject)object;
        colorPanel.setBackground(colorObject.colorValue());
        nameLabel.setText(colorObject.getName());
        setBorder(new javax.swing.border.TitledBorder(colorObject.getDescription()));        
    }

    /** Set width of caption */
    public void setCaptionWidth(int captionWidth) {
        this.captionWidth = captionWidth;
        resizeComponents();
    }

    /** Update object */
    public void updateValue() {
        if(colorObject!=null){
            colorObject.setColorValue(colorPanel.getBackground());
        }
    }
    
    /** Reset the edited value */
    public void resetValue(){
        colorPanel.setBackground(colorObject.colorValue());
    }
    
    /** Set the parent editor window */
    public void setParent(XmlDataStoreEditor parent){
    }

    /** The helper data for this object has changed */
    public void helperDataChanged() {
    }

    /** Resize all the components */
    private void resizeComponents(){
        java.awt.Dimension d = nameLabel.getPreferredSize();
        nameLabel.setPreferredSize(new java.awt.Dimension(captionWidth, 20));
        //valueField.setSize(getWidth() - nameLabel.getWidth(), valueField.getHeight());        
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        colorPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("Color value"));
        add(jPanel1, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        nameLabel.setText("jLabel1");
        jPanel3.add(nameLabel);

        add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout(5, 5));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton1, java.awt.BorderLayout.EAST);

        colorPanel.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.add(colorPanel, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    /** Change the colour */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(colorObject!=null){
            java.awt.Color newColor = javax.swing.JColorChooser.showDialog(this, "Choose a color", colorPanel.getBackground());
            if(newColor!=null){
                colorPanel.setBackground(newColor);        
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
    
}
