/* =================================================================
 *                     conneXience Data Pipeline
 * =================================================================
 *
 * Copyright 2006 Hugo Hiden and Adrian Conlin
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.pipeline.gui.xmlstorage.xmldatatypes;
import org.pipeline.gui.xmlstorage.*;
import org.pipeline.core.xmlstorage.*;
import org.pipeline.core.xmlstorage.xmldatatypes.*;

import org.pipeline.gui.xmlstorage.datechooser.*;

import java.util.*;
import java.text.*;

/**
 * This panel provides an editor for an XmlDateObject
 * @author  hugo
 */
public class XmlDateDataObjectEditor extends javax.swing.JPanel implements XmlDataObjectEditor {
    /** Object being edited */
    private XmlDateDataObject dateObject = null;
    
    /** Selected date */
    private Date newDate = null;
    
    /** Caption width */
    private int captionWidth = 0;
    
    /** Parent container */
    private XmlDataStoreEditor parent;
    
    /** Formatter */
    private DateFormat format = DateFormat.getDateTimeInstance();
    
    /** Creates new form XmlDateDataObjectEditor */
    public XmlDateDataObjectEditor() {
        initComponents();
    }

    /** Set the object being edited */
    public void setObject(XmlDataObject object) {
        dateObject = (XmlDateDataObject)object;
        newDate = dateObject.dateValue();
        dateDisplay.setText(format.format(newDate));
        nameLabel.setText(dateObject.getName());
        setBorder(new javax.swing.border.TitledBorder(dateObject.getDescription()));
    }

    /** Set the width of the caption */
    public void setCaptionWidth(int captionWidth) {
        this.captionWidth = captionWidth;
        resizeComponents();
    }

    /** Update the object */
    public void updateValue() {
        dateObject.setDateValue(newDate);
    }
    
    /** Reset the edited value */
    public void resetValue(){
        newDate = dateObject.dateValue();
        dateDisplay.setText(format.format(newDate));        
    }
    
    /** Set the parent editor window */
    public void setParent(XmlDataStoreEditor parent){
        this.parent = parent;
    }
    
    /** The helper data for this object has changed */
    public void helperDataChanged() {
    }
    
    /** Resize all the components */
    private void resizeComponents(){
        java.awt.Dimension d = nameLabel.getPreferredSize();
        nameLabel.setPreferredSize(new java.awt.Dimension(captionWidth, 20));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dateDisplay = new javax.swing.JTextField();
        changeDate = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("Date value"));
        add(jPanel1, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        nameLabel.setText("jLabel1");
        jPanel3.add(nameLabel);

        add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout(5, 0));

        dateDisplay.setEditable(false);
        dateDisplay.setText("jTextField1");
        jPanel4.add(dateDisplay, java.awt.BorderLayout.CENTER);

        changeDate.setText("...");
        changeDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDateActionPerformed(evt);
            }
        });

        jPanel4.add(changeDate, java.awt.BorderLayout.EAST);

        add(jPanel4, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    /** Get the new date */
    private void changeDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDateActionPerformed
        if(dateObject!=null){
            DateDialog dialog = new DateDialog((java.awt.Frame)null, true);
            dialog.setVisible(true);
            if(dialog.getDate()!=null){
                newDate = dialog.getDate();
                dateDisplay.setText(format.format(newDate));
            }
        }
    }//GEN-LAST:event_changeDateActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeDate;
    private javax.swing.JTextField dateDisplay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
    
}
