/* =================================================================
 *                     conneXience Data Pipeline
 * =================================================================
 *
 * Copyright 2006 Hugo Hiden and Adrian Conlin
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.pipeline.gui.xmlstorage.xmldatatypes;
import org.pipeline.gui.xmlstorage.*;
import org.pipeline.core.xmlstorage.*;
import org.pipeline.core.xmlstorage.xmldatatypes.*;

import java.io.*;

/**
 * This panel provides an editor for a file within an XmlDataObject
 * @author  hugo
 */
public class XmlFileDataObjectEditor extends javax.swing.JPanel implements XmlDataObjectEditor {
    /** Data object */
    XmlFileDataObject fileObject = null;
    
    /** New file to store */
    private File updatedFile;
    
    /** Caption width */
    private int captionWidth = 0;
    
    /** Parent container */
    private XmlDataStoreEditor parent;
    
    /** Creates new form XmlFileDataObjectEditor */
    public XmlFileDataObjectEditor() {
        initComponents();
    }
    
    /** Set the object being edited */
    public void setObject(XmlDataObject object) {
        fileObject = (XmlFileDataObject)object;
        updatedFile = fileObject.fileValue();
        
        
        displayFileName();
        nameLabel.setText(fileObject.getName());
        setBorder(new javax.swing.border.TitledBorder(fileObject.getDescription()));
    }

    /** Display the file name */
    private void displayFileName(){
        if(updatedFile!=null){
            fileDisplay.setText(updatedFile.getName());
        } else {
            fileDisplay.setText("");
        }
    }
    
    /** Set the width of the caption */
    public void setCaptionWidth(int captionWidth) {
        this.captionWidth = captionWidth;
        resizeComponents();
    }

    /** Update the object */
    public void updateValue() {
        fileObject.setFileValue(updatedFile);
    }
    
    /** Reset the edited value */
    public void resetValue(){
        updatedFile = fileObject.fileValue();
        displayFileName();      
    }
    
    /** Set the parent editor window */
    public void setParent(XmlDataStoreEditor parent){
        this.parent = parent;
    }
    
    /** The helper data for this object has changed */
    public void helperDataChanged() {
    }
    
    /** Resize all the components */
    private void resizeComponents(){
        java.awt.Dimension d = nameLabel.getPreferredSize();
        nameLabel.setPreferredSize(new java.awt.Dimension(captionWidth, 20));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        changeButton = new javax.swing.JButton();
        fileDisplay = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        add(jPanel1, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        nameLabel.setText("jLabel1");
        jPanel3.add(nameLabel);

        add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout(5, 0));

        changeButton.setText("...");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        jPanel4.add(changeButton, java.awt.BorderLayout.EAST);

        fileDisplay.setEditable(false);
        fileDisplay.setText("jTextField1");
        jPanel4.add(fileDisplay, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    /** Change the file */
    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser(updatedFile);
     
        if(fileObject.isDirectory()){
            chooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        } else {
            chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        }           
        
        chooser.showOpenDialog(this);
        
        if(chooser.getSelectedFile()!=null){
            updatedFile = chooser.getSelectedFile();
            displayFileName();
        }

    }//GEN-LAST:event_changeButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField fileDisplay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
    
}
