/* =================================================================
 *                     conneXience Data Pipeline
 * =================================================================
 *
 * Copyright 2006 Hugo Hiden and Adrian Conlin
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.pipeline.gui.xmlstorage.xmldatatypes;
import org.pipeline.gui.xmlstorage.*;
import org.pipeline.core.xmlstorage.*;
import org.pipeline.core.xmlstorage.xmldatatypes.*;

/**
 * This class provides a string editor panel
 * @author  hugo
 */
public class XmlStringDataObjectEditor extends javax.swing.JPanel implements XmlDataObjectEditor {
    /** String data object being edited */
    private XmlStringDataObject stringObject = null;
    
    /** Width of caption */
    private int captionWidth = 0;
    
    /** Creates new form XmlStringDataObjectEditor */
    public XmlStringDataObjectEditor() {
        initComponents();
        captionWidth = getWidth() / 2;
    }

    /** Set the object being edited */
    public void setObject(XmlDataObject object) {
        stringObject = (XmlStringDataObject)object;
        if(stringObject!=null){
            nameLabel.setText(stringObject.getName());
            valueField.setText(stringObject.stringValue());
            setBorder(new javax.swing.border.TitledBorder(stringObject.getDescription()));
        }
    }

    /** Set caption width */
    public void setCaptionWidth(int captionWidth) {
        this.captionWidth = captionWidth;
        resizeComponents();
    }

    /** Update the edited object */
    public void updateValue() {
        if(stringObject!=null){
            stringObject.setStringValue(valueField.getText());
        }
    }
    
    /** Reset the edited value */
    public void resetValue(){
        valueField.setText(stringObject.stringValue());
    }
    
    /** Set the parent editor window */
    public void setParent(XmlDataStoreEditor parent){
    }
    
    /** The helper data for this object has changed */
    public void helperDataChanged() {
    }
    
    /** Resize all the components */
    private void resizeComponents(){
        java.awt.Dimension d = nameLabel.getPreferredSize();
        nameLabel.setPreferredSize(new java.awt.Dimension(captionWidth, 20));
        valueField.setSize(getWidth() - nameLabel.getWidth(), valueField.getHeight());        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        valueField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("An editor"));
        nameLabel.setText("jLabel1");
        jPanel1.add(nameLabel);

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        valueField.setMaximumSize(new java.awt.Dimension(400, 2147483647));
        jPanel2.add(valueField, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        add(jPanel4, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField valueField;
    // End of variables declaration//GEN-END:variables
    
}
