/* =================================================================
 *                     conneXience Data Pipeline
 * =================================================================
 *
 * Copyright 2006 Hugo Hiden and Adrian Conlin
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.pipeline.core.matrix.table;
import org.pipeline.core.matrix.*;

/**
 * This panel displays a matrix in a JTable.
 * @author  hugo
 */
public class MatrixTablePanel extends javax.swing.JPanel {
    
    /** Creates new form MatrixTablePanel */
    public MatrixTablePanel(Matrix m, boolean writable) {
        initComponents();

        matrixTable.setModel(new MatrixTableModel(m, writable));
        matrixTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        // Set preferred column widths
        int size = matrixTable.getColumnModel().getColumnCount();
        for(int i=0;i<size;i++){
            matrixTable.getColumnModel().getColumn(i).setMinWidth(75);
        }        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tableScroller = new javax.swing.JScrollPane();
        matrixTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(500, 400));
        matrixTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        matrixTable.setTableHeader(null);
        tableScroller.setViewportView(matrixTable);

        add(tableScroller, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable matrixTable;
    private javax.swing.JScrollPane tableScroller;
    // End of variables declaration//GEN-END:variables
    
}
