/*
 * WorkflowInvocationReport.java
 */

package com.connexience.server.workflow.engine;

import org.pipeline.core.xmlstorage.*;
import org.pipeline.core.drawing.model.*;

import java.util.*;

/**
 * This class holds a report of a finished workflow invocation. It contains
 * a copy of the drawing data and the execution reports generated by the drawing.
 * @author hugo
 */
public class WorkflowInvocationReport implements XmlStorable {
    /** Drawing data object */
    private XmlDataStore drawingData;
    
    /** Workflow reports */
    private Hashtable executionReports;
    
    /** Empty constructor */
    public WorkflowInvocationReport() {
    }
    
    /** Create from a WorkflowInvocation object */
    public WorkflowInvocationReport(WorkflowInvocation invocation) throws WorkflowInvocationException {
        try {
            drawingData = ((DefaultDrawingModel)invocation.getDrawing()).storeObject();
            executionReports = invocation.getExecutionReports();
        } catch (Exception e){
            throw new WorkflowInvocationException("Error creating invocation report: " + e.getMessage());
        }
    }
    
    /** Get the drawing data */
    public XmlDataStore getDrawingData(){
        return drawingData;
    }
    
    /** Get the list of execution reports */
    public Hashtable getExecutionReports(){
        return executionReports;
    }

    /** Store this object */
    public XmlDataStore storeObject() throws XmlStorageException {
        XmlDataStore store = new XmlDataStore("WorkflowInvocationReport");
        
        return store;
    }

    /** Recreate this object from storage */
    public void recreateObject(XmlDataStore store) throws XmlStorageException {

    }    
}