package com.connexience.server.util.logging;

/**
 * Created by IntelliJ IDEA.
 * User: TempAdmin
 * Date: 31-Dec-2009
 * Time: 19:51:53
 * To change this template use File | Settings | File Templates.
 */
public enum Operation
{
  REGISTER,
  LOGIN, LOGOUT,
  RUN_WORKFLOW, READ_DATA, WRITE_DATA,
  MAKE_FRIEND, MAKE_GROUP, JOIN_GROUP,
  NEW_SERVICE, NEW_WORKFLOW,
  NO_LONGER_FRIEND, LEAVE_GROUP,
  SHARE_DATA, SHARE_DATA_WITH_GROUP,
  UNSHARE_DATA, UNSHARE_DATA_WIH_GROUP,
  SHARE_WORKFLOW, SHARE_WORKFLOW_WITH_GROUP,
  UNSHARE_WORKFLOW, UNSHARE_WORKFLOW_WITH_GROUP,
  SHARE_SERVICE, SHARE_SERVICE_WITH_GROUP,
  UNSHARE_SERVICE, UNSHARE_SERVICE_WITH_GROUP,
  DO_NOTHING
}
