/*
 * GeneralDialog.java
 *
 * Created on 14 October 2006, 20:40
 */

package org.pipeline.gui.xmlstorage.table;


/**
 * This dialog can contain a frame which is placed at the centre
 * of a border layout with OK and cancel buttons on the bottom.
 * @author  hugo
 */
public class ExternalXmlDataObjectDialog extends javax.swing.JDialog {
    /** Dialog accepted flag */
    boolean dialogAccepted = false;
    
    /** Content panel */
    ExternalXmlDataObjectEditor.XmlDataObjectEditorPanel contentPanel;
    
    /** Creates new form GeneralDialog */
    public ExternalXmlDataObjectDialog(java.awt.Frame parent, boolean modal, ExternalXmlDataObjectEditor.XmlDataObjectEditorPanel contentPanel) {
        super(parent, modal);
        initComponents();
        this.contentPanel = contentPanel;
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);
        pack();
        this.setLocationRelativeTo(null);
    }
       
    /** Was the dialog accepted */
    public boolean isDialogAccepted(){
        return dialogAccepted;
    }
    
    /** Get the editor panel */
    public ExternalXmlDataObjectEditor.XmlDataObjectEditorPanel getEditorPanel(){
        return contentPanel;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dialogAccepted = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dialogAccepted = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dialogAccepted = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
